[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py | python",
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py migrate --noinput",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn recovery_center.wsgi --log-file - --bind 0.0.0.0:$PORT"
