[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && python /tmp/get-pip.py --break-system-packages",
  "python -m pip install --upgrade pip setuptools wheel --break-system-packages",
  "python -m pip install --no-cache-dir -r requirements.txt --break-system-packages"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate --noinput && gunicorn recovery_center.wsgi --log-file - --bind 0.0.0.0:$PORT"
